# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        utilisateurs:
            entity:
                class: BlogBundle:User
                property: login

    encoders:
        BlogBundle\Entity\User : plaintext

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        blog:
            pattern: ^/(index|utilisateur|login_check|logout|signalement|thematiques)
            form_login:
                login_path: /
                check_path: /login_check
                default_target_path: blog_homepage
            logout:
                path: /logout
                target: /

        accueil:
            pattern: ^/
            anonymous: ~


            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
