services:
    app.serviceController:
        class:     BlogBundle\Controller\ServiceController
        arguments: ["@service_container","@session"]

    app.commentaireController:
        class:    BlogBundle\Controller\CommentaireController
        arguments: ["@service_container","@session"]