<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAfter($date)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.dateCreation >= :date')
            ->setParameter('date', $date)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
