<?php

namespace BlogBundle\Repository;

/**
 * ChoixthemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixthemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserAndTheme($user,$theme)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.user = :user')
            ->setParameter('user', $user)
            ->andWhere('a.theme = :theme')
            ->setParameter('theme', $theme)
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
