<?php

namespace BlogBundle\Repository;

/**
 * ChoixthemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixthemeRepository extends \Doctrine\ORM\EntityRepository
{
}
