<?php

namespace BlogBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserAndArticle($user,$article)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.utilisateur = :user')
            ->setParameter('user', $user)
            ->andWhere('a.article = :article')
            ->setParameter('article', $article)
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
