<?php

namespace BlogBundle\Repository;

/**
 * Signalement_CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Signalement_CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
