<?php

namespace BlogBundle\Repository;

/**
 * Signalement_ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Signalement_ArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
