<?php

namespace BlogBundle\Repository;

/**
 * SignalementcommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementcommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
