<?php

namespace BlogBundle\Repository;

/**
 * SignalementarticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementarticleRepository extends \Doctrine\ORM\EntityRepository
{
}
