blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

blog_user:
    resource: "@BlogBundle/Resources/config/routing/user.yml"
    prefix:   /user

blog_signalement_commentaire:
    resource: "@BlogBundle/Resources/config/routing/signalement_commentaire.yml"
    prefix: /signalement

blog_homepage:
    path:     /index
    defaults: { _controller: BlogBundle:Default:index }

utilisateur_profil:
    path:     /utilisateurs/profil/{id}
    defaults:
        _controller: BlogBundle:Utilisateur:profil
        id: null

thematiques_list:
    path:     /thematiques/list
    defaults: { _controller: BlogBundle:Thematique:list }

thematiques_search:
    path:     /thematiques/search/{str}
    defaults:
        _controller: BlogBundle:Thematique:search
        str: null

login:
    path: /
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

note_article:
    path: /notes/add/{id}
    defaults: {_controller: BlogBundle:Note:add}
