blog_homepage:
    path:     /index
    defaults: { _controller: BlogBundle:Default:index }

signalements_list:
    path:     /signalements/list
    defaults: { _controller: BlogBundle:Signalement:list }

signalements_add:
    path:     /signalements/add
    defaults: { _controller: BlogBundle:Signalement:add }

utilisateur_profil:
    path:     /utilisateurs/profil/{id}
    defaults:
        _controller: BlogBundle:Utilisateur:profil
        id: null

thematiques_list:
    path:     /thematiques/list
    defaults: { _controller: BlogBundle:Thematique:list }

thematiques_search:
    path:     /thematiques/search/{str}
    defaults:
        _controller: BlogBundle:Thematique:search
        str: null

login:
    path: /
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
