BlogBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
            column: Contenu
        date:
            type: datetime
            column: Date

    manyToOne:
        utilisateur:
            targetEntity: User
            inversedBy: commentaires

        article:
            targetEntity: Article
            inversedBy: commentaires

    oneToMany:
        signalementscommentaire:
            targetEntity: Signalementcommentaire
            mappedBy: commentaire
    lifecycleCallbacks: {  }
