BlogBundle\Entity\Signalementarticle:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\SignalementarticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
            column: Contenu
    lifecycleCallbacks: {  }
