BlogBundle\Entity\Signalementcommentaire:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\SignalementcommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: text
            column: Contenu

    manyToOne:
        commentaire:
            targetEntity: Commentaire
            inversedBy: signalementscommentaire

        utilisateur:
            targetEntity: User
            inversedBy: signalementscommentaire
