BlogBundle\Entity\Theme:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom

        description:
            type: text
            column: Description

    oneToMany:
        themeassociation:
            targetEntity: Choixtheme
            mappedBy: theme

    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: themes

    lifecycleCallbacks: {  }
